power.data<-read.delim("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
power.subset <- subset(power.data, Date == "1/2/2007" | Date == "2/2/2007")
datetime <- strptime(paste(power.subset$Date, power.subset$Time), format="%d/%m/%Y %H:%M:%S")
png(filename="Plot4.png", width=480, height=480)
par(mfrow=c(2,2))
with(power.subset,{
  plot(datetime, power.subset[,"Global_active_power"], type="l",ylab="Global Active Power (kilowatts)", xlab="", main="")
  plot(datetime,power.subset[,"Voltage"],type="l",ylab="Voltage",xlab="",main="")
  plot(datetime,power.subset[,"Sub_metering_1"],type="l",ylab="Energy sub metering",xlab="",main="")
  lines(datetime,power.subset[,"Sub_metering_2"],col="red")
  lines(datetime,power.subset[,"Sub_metering_3"],col="blue")
  legend("topright",pch=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(datetime,power.subset[,"Global_reactive_power"],type="l",ylab="Global_reactive_power",xlab="",main="")
})
dev.off()